[package]
name = "ferris_says"
version = "0.1.0"
authors = ["Jason Davila <jasond@scribd.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
